[mypy]
python_version = 3.12
ignore_missing_imports = true
warn_return_any = false
warn_unused_ignores = false
disable_error_code = assignment,return-value,attr-defined,misc,var-annotated,index,import-untyped,name-defined

[mypy-agent.core.voice.wake_word]
ignore_errors = true
